In [11]:
import numpy as np

In [25]:
array = np.array([0,1,2,3,4,6,7,8,9,10,11,12,13,14,15]) # 1-15 dizi oluşturduk

In [26]:
print(array.shape)

(15,)


In [27]:
a = array.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
print(a.shape)

(3, 5)


In [30]:
print(a.ndim)

2


In [31]:
print(a.dtype)

int64


In [32]:
print(a.size)

15


In [33]:
print(type(a))

<class 'numpy.ndarray'>


In [40]:
print(np.random.rand())

0.11042977804624099


In [41]:
print(np.random.rand(5))

[0.57520513 0.08109317 0.53141858 0.16898208 0.02956811]


In [39]:
print(np.random.randn(4))

[-0.8163201  -1.04276749  0.59392296 -0.16389545]


In [42]:
print(np.random.rand(2, 3))

[[0.20453974 0.44074915 0.70571594]
 [0.30549859 0.80846545 0.11422532]]


In [43]:
print(np.random.randint(10, 50, size=5))

[28 46 11 19 10]


In [46]:
dizi = [10, 20, 30, 40]
print(np.random.choice(dizi))

10


In [59]:
print(np.empty((3, 3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
nd_array = np.linspace(0, 10, 4)
nd_array

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])